### ISSUE TITLE
CSS displays in a search result

### ISSUE THREAD

**Issue by stevevance** [datamade/chi-councilmatic#117] opened 2016-02-03 01:20 UTC
<img width="910" alt="screenshot 2016-02-02 19 19 47" src="https://cloud.githubusercontent.com/assets/1330459/12769978/0820b160-c9e2-11e5-95b3-1eb5955d4a91.png">
https://chicago.councilmatic.org/search/?q=pedestrian+stret

**Comment by cathydeng** [comment] 2016-02-03 06:17
duplicate of #75

**Closed by cathydeng** 2016-02-03 06:17 UTC
