### ISSUE TITLE
All aldermen missing, only one incorrect committee showing

### ISSUE THREAD

**Issue by derekeder** [datamade/chi-councilmatic#254] opened 2019-05-30 03:01 UTC
Last week on May 20, the new Mayor and City Council were sworn in. Councilmatic does not seem to be reflecting these changes:

Aldermen page:

<img width="1275" alt="Screen Shot 2019-05-29 at 9 57 40 PM" src="https://user-images.githubusercontent.com/919583/58605274-d560be00-825c-11e9-93f7-7baea4e78809.png">

Committees page:

<img width="1272" alt="Screen Shot 2019-05-29 at 9 57 48 PM" src="https://user-images.githubusercontent.com/919583/58605283-da257200-825c-11e9-80d9-b9be98013a87.png">

**Comment by fgregg** [comment] 2019-05-30 14:36
I think the problem is either in the scrapers (easy to confirm by checking ocd.datamade.us). In particular, I suspects that the end dates for the current council terms may not be in source system which is needed for 

https://github.com/datamade/django-councilmatic/blob/5d567450ce4a50bee36843de31b4b03872a59b53/councilmatic_core/models.py#L615-L627


 Also there are some settings that need to be updated for the 2019 legislative session.

Here's at least one setting:

https://github.com/datamade/chi-councilmatic/blob/ef9855e22d0446420a6c914623e76a6e9b840b00/councilmatic/settings_jurisdiction.py#L10

**Comment by hancush** [comment] 2019-05-30 17:46
def on the settings. i also did a little spelunking in the ocd database and found that people hadn't been updated since march and organizations hadn't been updated since december???

```
opencivicdata=# select max(p.updated_at) from opencivicdata_membership as m join opencivicdata_organization as o on m.organization_id = o.id join opencivicdata_person as p on m.person_id = p.id where o.jurisdiction_id = 'ocd-jurisdiction/country:us/state:il/place:chicago/government';
              max
-------------------------------
 2019-03-20 02:46:27.899039+00
(1 row)
```

```
opencivicdata=# select max(updated_at) from opencivicdata_organization where jurisdiction_id = 'ocd-jurisdiction/country:us/state:il/place:chicago/government';
              max
-------------------------------
 2018-12-16 04:19:55.620613+00
(1 row)
```

that seems funny to me.

**Comment by hancush** [comment] 2019-06-10 19:09
this was an issue with null end dates and null vote values. it was resolved in https://github.com/opencivicdata/scrapers-us-municipal/pull/280!

**Closed by hancush** 2019-06-10 19:09 UTC
